name: Build docker

on:
  push:

env:
  REGISTRY: ghcr.io
  PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
  PLAID_SECRET_DEVELOPMENT: ${{ secrets.PLAID_SECRET_DEVELOPMENT }}
  PLAID_ENV: development
  PLAID_PRODUCTS: auth,transactions
  PLAID_COUNTRY_CODES: NL

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_ACCESS_TOKEN }}

    - name: Build image
      run: docker compose build

    - name: Push image
      run: docker compose push