name: Build docker

on:
  push:

env:
  REGISTRY: ghcr.io
  PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
  PLAID_SECRET_DEVELOPMENT: ${{ secrets.PLAID_SECRET_DEVELOPMENT }}
  PLAID_ENV: development
  PLAID_PRODUCTS: auth,transactions
  PLAID_COUNTRY_CODES: NL
  IMAGE_NAME_CLIENT: ${{ github.repository }}/pattern-client
  IMAGE_NAME_SERVER: ${{ github.repository }}/pattern-server

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_ACCESS_TOKEN }}

    - name: Client - Extract metadata (tags, labels) for Docker
      id: meta-client
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLIENT }}

    - name: Client - Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./client/
        push: true
        tags: ${{ steps.meta-client.outputs.tags }}
        labels: ${{ steps.meta-client.outputs.labels }}
